# Generated by Django 2.0.2 on 2019-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='descriptionDosAbout',
            field=models.TextField(blank='true', null='true', verbose_name='Descripción dos'),
        ),
    ]
