# Generated by Django 2.0.2 on 2019-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_descriptiondosabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('descriptionDos', models.TextField(verbose_name='Descripción Dos')),
                ('descriptionTres', models.TextField(verbose_name='Descripción Tres')),
                ('descriptionCuatro', models.TextField(verbose_name='Descripción Cuatro')),
                ('subDescripcionDos', models.TextField(verbose_name='Sub Descripción Dos')),
                ('subDescripcionTres', models.TextField(verbose_name='Sub Descripción Tres')),
                ('subDescripcionCuatro', models.TextField(verbose_name='Sub Descripción Cuatro')),
                ('under_title', models.CharField(max_length=200, verbose_name='Sub Título')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Inicio',
                'verbose_name_plural': 'Inicio',
                'ordering': ['-created'],
            },
        ),
    ]
