# Generated by Django 2.0.2 on 2019-04-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
    ]
